# Label definitions for GitHub Actions sync
# See workflow: .github/workflows/labels.yml

labels:
  - name: "type: bug"
    color: "d73a4a"
    description: "Bug 报告 / 缺陷"
  - name: "type: feature"
    color: "a2eeef"
    description: "新功能"
  - name: "type: enhancement"
    color: "84b6eb"
    description: "增强优化"
  - name: "type: docs"
    color: "0075ca"
    description: "文档"
  - name: "type: chore"
    color: "cfd3d7"
    description: "杂项（依赖/脚手架/CI 等）"

  - name: "scope: theme"
    color: "5319e7"
    description: "主题（src/wechat/themes/）"
  - name: "scope: library"
    color: "5319e7"
    description: "组件/模板/套版（src/wechat/library/）"
  - name: "scope: export"
    color: "5319e7"
    description: "导出/内联（wechatStyles/inlineWeChat）"
  - name: "scope: editor"
    color: "5319e7"
    description: "编辑器 UI/交互（WeChatEditor）"

  - name: "good first issue"
    color: "7057ff"
    description: "适合新贡献者"
  - name: "help wanted"
    color: "008672"
    description: "需要帮助"
  - name: "blocked"
    color: "b60205"
    description: "被阻塞"
  - name: "needs repro"
    color: "fbca04"
    description: "需要复现步骤"
  - name: "needs design"
    color: "fbca04"
    description: "需要设计讨论"

  - name: "wechat: paste"
    color: "0e8a16"
    description: "公众号后台粘贴相关"
  - name: "wechat: export"
    color: "0e8a16"
    description: "导出相关"

  - name: "request: bundle"
    color: "1d76db"
    description: "请求生成可下载的构建 ZIP（Actions artifact）"
